### ISSUE TITLE
csv file is missing

### ISSUE THREAD

**Issue by kiransaleem13** [Sarmentor/InventoryManagement#1]
you didn't upload the csv file

**Comment by Sarmentor** [comment]
Hi, 
Please check if uploaded files are usefull
Best Regards

**Comment by kiransaleem13** [comment]
There were some syntax issues because now the netlogo platform is 6.1. I
resolved those issues but now the error was about the csv file.

**Comment by Sarmentor** [comment]
If you wish please make a fork or propose a PR with your updates. Thank you.Best RegardsOn Apr 9, 2020 20:34, kiransaleem13 <notifications@github.com> wrote:

There were some syntax issues because now the netlogo platform is 6.1. I

resolved those issues but now the error was about the csv file.



On Thu, 9 Apr 2020, 8:39 pm Rui Portocarrero Sarmento, <

**Comment by Sarmentor** [comment]
Hi,

Have you managed to get it fully working?

Best Regards

**Comment by kiransaleem13** [comment]
Yes. Thank you

**Comment by Sarmentor** [comment]
Closed issue. Thank you to @kiransaleem13 for calling attention to lacking .csv example files in the repository.
